# Generated by Django 5.0.6 on 2024-07-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="aka",
        ),
    ]
