# Generated by Django 5.0.6 on 2024-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_type_alter_profile_aka"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.AlterField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[("anonymous", "Anonymous"), ("personal", "Personal")],
                default="anonymous",
                max_length=10,
            ),
        ),
    ]
