# Generated by Django 5.0.6 on 2024-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
    ]
