# Generated by Django 5.0.6 on 2024-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_profile_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[("anonymous", "Anonymous"), ("personal", "Personal")],
                default="anonymous",
                max_length=10,
                verbose_name="Profile Type",
            ),
        ),
    ]
