# Generated by Django 5.0.6 on 2024-07-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_slug_pinnedposts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PinnedPosts",
            new_name="PinnedPost",
        ),
    ]
