# Generated by Django 5.0.7 on 2024-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_pinnedposts_pinnedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="readtime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
