# Generated by Django 5.0.7 on 2024-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_readtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="rendered_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
