# Generated by Django 5.0.7 on 2024-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="readtime",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(editable=False, max_length=255),
        ),
    ]
