# Generated by Django 5.0.6 on 2024-07-08 05:36

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
