# Generated by Django 5.0.6 on 2024-07-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsLetter",
            new_name="NewsLetterEntry",
        ),
    ]
