# Generated by Django 5.0.6 on 2024-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_remove_newsletterentry_joined_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterentry",
            name="entry_id",
            field=models.UUIDField(
                default=327628554256415036489503988386939783198, unique=True
            ),
        ),
    ]
