# Generated by Django 5.0.6 on 2024-07-09 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_alter_newsletterentry_entry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterentry",
            name="entry_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
