# Generated by Django 5.0.6 on 2024-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_alter_newsletterentry_entry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterentry",
            name="entry_id",
            field=models.CharField(default="4310541258", max_length=255, unique=True),
        ),
    ]
