# Generated by Django 5.0.7 on 2024-07-12 03:33

import apps.newsletter.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_alter_newsletterentry_entry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterentry",
            name="entry_id",
            field=models.CharField(
                default=apps.newsletter.utils.generate_entry_id,
                max_length=255,
                unique=True,
            ),
        ),
    ]
