# Generated by Django 5.0.6 on 2024-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_bio_profile_discord_profile_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="type",
            field=models.CharField(
                choices=[("anonym", "Anonymous"), ("personal", "Personal")],
                default="anonym",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="aka",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Also Known As"
            ),
        ),
    ]
