# Generated by Django 5.0.6 on 2024-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_profile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="/",
            ),
        ),
    ]
